spring:
    application:
        name: gateway

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true

            routes:
                - id: auth-service
                  uri: lb://auth-service
                  predicates:
                      - Path=/_captcha,/_checkCaptcha,/register,/login,/refresh,/activate,/_checkUsernameUnique

                - id: user-service
                  uri: lb://user-service
                  predicates:
                      - Path=/profile,/userProfile,/userPosts,/updateNickname,/updatePassword,/updateAvatar,/sys-ctrl/users,/sys-ctrl/banUser

                - id: post-service
                  uri: lb://post-service
                  predicates:
                      - Path=/post/**,/postInfo,/list,/postContent,/postTitle,/tags**,/tag**,/sys-ctrl/tag**,/sys-ctrl/tagOption**

                - id: comment-service
                  uri: lb://comment-service
                  predicates:
                      - Path=/getComments,/getReplies,/doComment,/doReply

                - id: search-service
                  uri: lb://search-service
                  predicates:
                      - Path=/search/**

                - id: sensitive-service
                  uri: lb://sensitive-service
                  predicates:
                      - Path=/sys-ctrl/sensitiveWord

                - id: monitor-service
                  uri: lb://monitor-service
                  predicates:
                      - Path=/systemInfo,/forumInfo
