spring:
  application:
    name: user-service

  profiles:
    active: local

  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false #关闭thymeleaf的页面缓存功能

  mail:
    host: smtp.qq.com
    default-encoding: UTF-8
    port: 465
    protocol: smtp
    username: a635818021
    password: mketvjzdkqwqbbfa
    properties:
      mail:
        smtp:
          auth: true #使用SMTP身份验证
          starttls:
            enable: true #开启SSL安全协议
            required: false
          ssl:
            enable: true

#关于邮件的自定义属性
mail:
  from: 635818021@qq.com #发送邮件的来源
  register:
    subject: "请查收您的验证码" #注册邮件的主题

server:
  port: 8081

