spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: ${bbs.db.un:root}
    password: ${bbs.db.pw:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${bbs.db.host:192.168.3.16}:${bbs.db.port:3306}/${bbs.db.database}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: ${bbs.db.packet}
  global-config:
    db-config:
      id-type: assign_id #默认是雪花算法生成ID，这里显式写出来了
      logic-delete-value: 1 #逻辑删除记录的值
      logic-not-delete-value: 0 #逻辑未删除记录的值
      logic-delete-field: deleted #逻辑删除对应的字段名